version: "3.8"

services:
  db:
    extends:
      file: ./docker-compose.db.yml
      service: mongodb

  api:
    image: daily-trends
    command: npm run start
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  scraper:
    image: daily-trends
    command: npm run scraper
    env_file:
      - .env.prod
    depends_on:
      - db
      - api

volumes:
  mongodb_data:
